<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;

class ProductionProductsSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate
        Product::truncate();

        // Data
        $data = [
            [
                'id' => 79,
                'category_id' => 5,
                'product_group_id' => null,
                'product_type_id' => 45,
                'product_model_id' => 56,
                'product_material_id' => 46,
                'product_color_id' => null,
                'product_size_id' => 6,
                'color' => '',
                'attribute' => '',
                'size' => '',
                'brand' => null,
                'name' => 'Whey Protein Concentrado Em Soro De Leite Tamanho 1kg',
                'slug' => 'whey-protein-concentrado-em-soro-de-leite-tamanho-1kg',
                'sku' => 'SUP-WHE-0024-STD-1KG',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '80.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 20,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930b6bf61925_1764800191.webp',
                'created_at' => '2025-12-03 22:16:31',
                'updated_at' => '2025-12-10 23:06:25',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 80,
                'category_id' => 5,
                'product_group_id' => null,
                'product_type_id' => 45,
                'product_model_id' => 56,
                'product_material_id' => 46,
                'product_color_id' => null,
                'product_size_id' => 6,
                'color' => 'Baunilha',
                'attribute' => null,
                'size' => '1kg',
                'brand' => null,
                'name' => 'Whey Protein Concentrado Em Soro De Leite – Baunilha Tamanho 1kg',
                'slug' => 'whey-protein-concentrado-em-soro-de-leite-baunilha-tamanho-1kg',
                'sku' => 'SUP-WHE-0023-BAU-1KG',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '80.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 20,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930bccacc57a_1764801738.webp',
                'created_at' => '2025-12-03 22:30:26',
                'updated_at' => '2025-12-10 22:58:18',
                'product_flavor_id' => 4,
                'variant_type' => 'flavor',
            ],
            [
                'id' => 81,
                'category_id' => 5,
                'product_group_id' => null,
                'product_type_id' => 45,
                'product_model_id' => 56,
                'product_material_id' => 46,
                'product_color_id' => null,
                'product_size_id' => 6,
                'color' => 'Natural',
                'attribute' => null,
                'size' => '1kg',
                'brand' => null,
                'name' => 'Whey Protein Concentrado Em Soro De Leite – Limão Tamanho 1kg',
                'slug' => 'whey-protein-concentrado-em-soro-de-leite-limao-tamanho-1kg',
                'sku' => 'SUP-WHE-0021-LIM-1KG',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '80.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 20,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930bfd8db337_1764802520.webp',
                'created_at' => '2025-12-03 22:31:19',
                'updated_at' => '2025-12-10 22:56:43',
                'product_flavor_id' => 3,
                'variant_type' => 'flavor',
            ],
            [
                'id' => 82,
                'category_id' => 4,
                'product_group_id' => null,
                'product_type_id' => 45,
                'product_model_id' => 56,
                'product_material_id' => 46,
                'product_color_id' => null,
                'product_size_id' => 6,
                'color' => 'Natural',
                'attribute' => null,
                'size' => '1kg',
                'brand' => null,
                'name' => 'Whey Protein Concentrado Em Soro De Leite – Natural Tamanho 1kg',
                'slug' => 'whey-protein-concentrado-em-soro-de-leite-natural-tamanho-1kg',
                'sku' => 'SUP-WHE-0020-NAT-1KG',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '80.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 20,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930bfbe67e40_1764802494.webp',
                'created_at' => '2025-12-03 22:49:54',
                'updated_at' => '2025-12-10 22:56:17',
                'product_flavor_id' => 6,
                'variant_type' => 'flavor',
            ],
            [
                'id' => 83,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 42,
                'product_model_id' => 48,
                'product_material_id' => 43,
                'product_color_id' => 3,
                'product_size_id' => 3,
                'color' => '',
                'attribute' => 'Exuberante trançada',
                'size' => '',
                'brand' => null,
                'name' => 'Blusa Frente Única Em Barbante Exuberante Trançada – Rosa Tamanho G',
                'slug' => 'blusa-frente-unica-em-barbante-exuberante-trancada-rosa-tamanho-g',
                'sku' => 'CRO-BLU-0005-ROS-G',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '150.00',
                'compare_at_price' => '200.00',
                'cost_price' => null,
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c2ba9254b_1764803258.webp',
                'created_at' => '2025-12-03 22:58:32',
                'updated_at' => '2025-12-15 18:10:04',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 84,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 42,
                'product_model_id' => 48,
                'product_material_id' => 43,
                'product_color_id' => 4,
                'product_size_id' => 3,
                'color' => 'Verde',
                'attribute' => 'Exuberante trançada',
                'size' => 'G',
                'brand' => null,
                'name' => 'Blusa Frente Única Em Barbante Exuberante Trançada – Verde Tamanho G',
                'slug' => 'blusa-frente-unica-em-barbante-exuberante-trancada-verde-tamanho-g',
                'sku' => 'CRO-BLU-0006-VRD-G',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '150.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c2d45248a_1764803284.webp',
                'created_at' => '2025-12-03 22:59:22',
                'updated_at' => '2025-12-03 23:08:04',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 85,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 42,
                'product_model_id' => 48,
                'product_material_id' => 43,
                'product_color_id' => 2,
                'product_size_id' => 3,
                'color' => 'Azul',
                'attribute' => 'Exuberante trançada',
                'size' => 'G',
                'brand' => null,
                'name' => 'Blusa Frente Única Em Barbante Exuberante Trançada – Azul Tamanho G',
                'slug' => 'blusa-frente-unica-em-barbante-exuberante-trancada-azul-tamanho-g',
                'sku' => 'CRO-BLU-0007-AZU-G',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '150.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c2ea9a0a1_1764803306.webp',
                'created_at' => '2025-12-03 23:03:23',
                'updated_at' => '2025-12-03 23:08:26',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 86,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 42,
                'product_model_id' => 54,
                'product_material_id' => 45,
                'product_color_id' => 1,
                'product_size_id' => 1,
                'color' => 'Preto',
                'attribute' => 'Elegante',
                'size' => 'G',
                'brand' => null,
                'name' => 'Blusa Tradicional Em Algodão Natural Elegante – Preto Tamanho P',
                'slug' => 'blusa-tradicional-em-algodao-natural-elegante-preto-tamanho-p',
                'sku' => 'CRO-BLU-0008-PRT-P',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '150.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c3013ff64_1764803329.webp',
                'created_at' => '2025-12-03 23:05:22',
                'updated_at' => '2025-12-03 23:08:49',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 87,
                'category_id' => 2,
                'product_group_id' => null,
                'product_type_id' => 37,
                'product_model_id' => 49,
                'product_material_id' => 39,
                'product_color_id' => 10,
                'product_size_id' => 2,
                'color' => '',
                'attribute' => 'Super confortável',
                'size' => '',
                'brand' => null,
                'name' => 'Biquíni Surf Em Lycra Premium Super Confortável – Branco Tamanho M',
                'slug' => 'biquini-surf-em-lycra-premium-super-confortavel-branco-tamanho-m',
                'sku' => 'PRA-BIQ-0010-BRA-M',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '70.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 50,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c5d742191_1764804055.webp',
                'created_at' => '2025-12-03 23:18:04',
                'updated_at' => '2025-12-03 23:34:56',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 88,
                'category_id' => 2,
                'product_group_id' => null,
                'product_type_id' => 37,
                'product_model_id' => 49,
                'product_material_id' => 39,
                'product_color_id' => 7,
                'product_size_id' => 3,
                'color' => 'Amarelo',
                'attribute' => 'Super confortável',
                'size' => 'G',
                'brand' => null,
                'name' => 'Biquíni Surf Em Lycra Premium Super Confortável – Amarelo Tamanho G',
                'slug' => 'biquini-surf-em-lycra-premium-super-confortavel-amarelo-tamanho-g',
                'sku' => 'PRA-BIQ-0011-AMA-G',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '70.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 50,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c8e099054_1764804832.webp',
                'created_at' => '2025-12-03 23:18:33',
                'updated_at' => '2025-12-03 23:33:52',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 89,
                'category_id' => 2,
                'product_group_id' => null,
                'product_type_id' => 37,
                'product_model_id' => 49,
                'product_material_id' => 39,
                'product_color_id' => 3,
                'product_size_id' => 1,
                'color' => 'Rosa',
                'attribute' => 'Super confortável',
                'size' => 'P',
                'brand' => null,
                'name' => 'Biquíni Surf Em Lycra Premium Super Confortável – Rosa Tamanho P',
                'slug' => 'biquini-surf-em-lycra-premium-super-confortavel-rosa-tamanho-p',
                'sku' => 'PRA-BIQ-0012-ROS-P',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '70.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 50,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/6930c9685b57d_1764804968.webp',
                'created_at' => '2025-12-03 23:19:05',
                'updated_at' => '2025-12-03 23:36:08',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 90,
                'category_id' => 2,
                'product_group_id' => null,
                'product_type_id' => 37,
                'product_model_id' => 49,
                'product_material_id' => 39,
                'product_color_id' => 1,
                'product_size_id' => 1,
                'color' => 'Preto',
                'attribute' => 'Super confortável',
                'size' => 'P',
                'brand' => null,
                'name' => 'Biquíni Surf Em Lycra Premium Super Confortável – Preto Tamanho P',
                'slug' => 'biquini-surf-em-lycra-premium-super-confortavel-preto-tamanho-p',
                'sku' => 'PRA-BIQ-0013-PRT-P',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '70.00',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 50,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => null,
                'created_at' => '2025-12-03 23:19:38',
                'updated_at' => '2025-12-03 23:36:59',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 91,
                'category_id' => 1,
                'product_group_id' => null,
                'product_type_id' => 33,
                'product_model_id' => 41,
                'product_material_id' => 36,
                'product_color_id' => 5,
                'product_size_id' => 2,
                'color' => '',
                'attribute' => 'Brilhe na Academia',
                'size' => '',
                'brand' => null,
                'name' => 'Legging Dryfit Em Microfibra Brilhe Na Academia – Cinza Tamanho M',
                'slug' => 'legging-dryfit-em-microfibra-brilhe-na-academia-cinza-tamanho-m',
                'sku' => 'FIT-LEG-0014-CIN-M',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '128.99',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 10,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6930cc24ae7f2_1764805668.jpg',
                'created_at' => '2025-12-03 23:45:26',
                'updated_at' => '2025-12-03 23:47:58',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 92,
                'category_id' => 1,
                'product_group_id' => null,
                'product_type_id' => 33,
                'product_model_id' => 41,
                'product_material_id' => 36,
                'product_color_id' => 8,
                'product_size_id' => 2,
                'color' => 'Colorido',
                'attribute' => 'Brilhe na Academia',
                'size' => 'M',
                'brand' => null,
                'name' => 'Legging Dryfit Em Microfibra Brilhe Na Academia – Colorido Tamanho M',
                'slug' => 'legging-dryfit-em-microfibra-brilhe-na-academia-colorido-tamanho-m',
                'sku' => 'FIT-LEG-0015-COL-M',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '128.99',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 10,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6930cc614dc6b_1764805729.jpg',
                'created_at' => '2025-12-03 23:45:55',
                'updated_at' => '2025-12-03 23:48:56',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 93,
                'category_id' => 1,
                'product_group_id' => null,
                'product_type_id' => 33,
                'product_model_id' => 41,
                'product_material_id' => 36,
                'product_color_id' => 6,
                'product_size_id' => 2,
                'color' => 'Vermelho',
                'attribute' => 'Brilhe na Academia',
                'size' => 'M',
                'brand' => null,
                'name' => 'Legging Dryfit Em Microfibra Brilhe Na Academia – Vermelho Tamanho M',
                'slug' => 'legging-dryfit-em-microfibra-brilhe-na-academia-vermelho-tamanho-m',
                'sku' => 'FIT-LEG-0016-VER-M',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '128.99',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 10,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6930cc82db029_1764805762.jpg',
                'created_at' => '2025-12-03 23:46:15',
                'updated_at' => '2025-12-03 23:49:30',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 94,
                'category_id' => 1,
                'product_group_id' => null,
                'product_type_id' => 33,
                'product_model_id' => 41,
                'product_material_id' => 36,
                'product_color_id' => 4,
                'product_size_id' => 5,
                'color' => 'Vermelho',
                'attribute' => 'Brilhe ',
                'size' => 'Único',
                'brand' => null,
                'name' => 'Legging Dryfit Em Microfibra Brilhe  – Verde Tamanho Único',
                'slug' => 'legging-dryfit-em-microfibra-brilhe-verde-tamanho-unico',
                'sku' => 'FIT-LEG-0017-VRD-UNI',
                'ean' => null,
                'description' => '',
                'marketing_description' => '',
                'price' => '128.99',
                'compare_at_price' => null,
                'cost_price' => null,
                'old_price' => null,
                'stock' => 10,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6930cca770f96_1764805799.jpg',
                'created_at' => '2025-12-03 23:46:33',
                'updated_at' => '2025-12-10 21:45:25',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 95,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 43,
                'product_model_id' => 55,
                'product_material_id' => 40,
                'product_color_id' => 11,
                'product_size_id' => 3,
                'color' => '',
                'attribute' => '',
                'size' => '',
                'brand' => null,
                'name' => 'Saia Longo Em Viscose – Marrom Tamanho G',
                'slug' => 'saia-longo-em-viscose-marrom-tamanho-g',
                'sku' => 'CRO-SAI-0018-MAR-G',
                'ean' => null,
                'description' => '<h1>Flua com Leveza e Estilo: A Saia Longa em Viscose que Você Merece</h1><p>

</p><p>Cansada de peças que sacrificam o conforto pela beleza? Imagine uma saia que abraça sua silhueta com suavidade, permitindo que você se mova livremente e esbanje elegância em qualquer ocasião. A Saia Longa em Viscose da ModaCrochê é a resposta para um guarda-roupa que une praticidade e sofisticação.</p><p>

</p><p><br></p><p>

</p><p>Confeccionada em pura <strong>viscose</strong>, esta saia proporciona uma sensação de toque macio e um caimento leve que acompanha seus passos com fluidez. A riqueza da cor <strong>marrom</strong> confere um toque de sofisticação natural, fácil de harmonizar com blusas e acessórios para criar looks memoráveis.</p><p>

</p><p><br></p>',
                'marketing_description' => 'Realce seu look com a Saia Longo Em Viscose – Marrom Tamanho G da ModaCrochê. Elegância e fluidez te esperam. Adquira a sua!',
                'price' => '25.00',
                'compare_at_price' => '50.00',
                'cost_price' => '5.00',
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6939ebdbddb93_1765403611.jpg',
                'created_at' => '2025-12-10 21:46:41',
                'updated_at' => '2025-12-12 23:39:39',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 96,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 43,
                'product_model_id' => 55,
                'product_material_id' => 43,
                'product_color_id' => 11,
                'product_size_id' => 3,
                'color' => 'Amarelo',
                'attribute' => null,
                'size' => 'G',
                'brand' => null,
                'name' => 'Saia Longo Em Barbante – Marrom Tamanho G',
                'slug' => 'saia-longo-em-barbante-marrom-tamanho-g',
                'sku' => 'CRO-SAI-0025-MAR-G',
                'ean' => null,
                'description' => '<h1>Deslumbre-se com a Saia Longo Artesanal em Barbante Marrom – Tamanho G</h1><p>

</p><p>Cansada de peças sem personalidade que não refletem seu estilo único? Imagine uma saia que combina o conforto do artesanal com a sofisticação da moda atual, perfeita para qualquer ocasião. Nossa Saia Longo em Barbante Marrom G é a resposta para quem busca autenticidade e elegância sem esforço.</p><p>

</p><p><br></p><p>

</p><p>Confeccionada com o mais puro e resistente barbante, esta saia oferece uma textura agradável ao toque e um caimento impecável. A tonalidade Marrom, rica e terrosa, é escolhida para proporcionar uma elegância natural e fácil de combinar, realçando a beleza do crochê feito à mão.</p><p>

</p><p><br></p>',
                'marketing_description' => 'Realce seu estilo com a Saia Longo Em Barbante – Marrom Tamanho G da ModaCrochê. Conforto e elegância em crochê artesanal. Garanta a sua!',
                'price' => '25.00',
                'compare_at_price' => '50.00',
                'cost_price' => '5.00',
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6939ef82979b3_1765404546.jpg',
                'created_at' => '2025-12-10 22:08:16',
                'updated_at' => '2025-12-12 23:36:00',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 98,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 50,
                'product_model_id' => 53,
                'product_material_id' => 42,
                'product_color_id' => 10,
                'product_size_id' => 2,
                'color' => '',
                'attribute' => 'Trançado Macramê',
                'size' => '',
                'brand' => null,
                'name' => 'Saída De Praia Midi Em Algodão Trançado Macramê – Branco Tamanho M',
                'slug' => 'saida-de-praia-midi-em-algodao-trancado-macrame-branco-tamanho-m',
                'sku' => 'CRO-SAI-0026-BRA-M',
                'ean' => null,
                'description' => '<h1>Saída de Praia Midi Macramê: O Toque Artesanal que Sua Elegância de Verão Pede</h1><p>

</p><p>Cansada de saídas de praia sem graça que não refletem seu estilo único? Imagine-se desfilando com uma peça que une a arte do macramê à leveza do algodão, transformando cada passo à beira-mar em um momento de pura sofisticação e conforto. Esta Saída de Praia Midi é a solução perfeita para quem busca elegância artesanal sem abrir mão da praticidade.</p><p><br></p><p>Confeccionada com <strong>100% algodão de alta qualidade</strong>, esta saída de praia oferece um toque suave e uma sensação arejada contra a pele, perfeita para os dias ensolarados. Sua cor <strong>Branco imaculado</strong> realça o bronzeado e harmoniza com qualquer biquíni ou maiô, garantindo um visual sempre fresco e sofisticado.</p>',
                'marketing_description' => 'Arrase com a Saída De Praia Midi Em Algodão Trançado Macramê – Branco Tamanho M da ModaCrochê. Estilo único para você. Compre já!',
                'price' => '150.00',
                'compare_at_price' => '200.00',
                'cost_price' => '60.00',
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6941c184e92db_1765917060.jpg',
                'created_at' => '2025-12-16 20:30:45',
                'updated_at' => '2025-12-16 20:31:42',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
            [
                'id' => 99,
                'category_id' => 3,
                'product_group_id' => null,
                'product_type_id' => 50,
                'product_model_id' => 53,
                'product_material_id' => 42,
                'product_color_id' => 2,
                'product_size_id' => 3,
                'color' => 'Branco',
                'attribute' => 'Trançado Macramê',
                'size' => 'G',
                'brand' => null,
                'name' => 'Saída De Praia Midi Em Algodão Trançado Macramê – Azul Tamanho G',
                'slug' => 'saida-de-praia-midi-em-algodao-trancado-macrame-azul-tamanho-g',
                'sku' => 'CRO-SAI-0027-AZL-G',
                'ean' => null,
                'description' => '<h1>A Aura do Verão: Saída De Praia Midi Em Algodão Trançado Macramê – Branco</h1><p>

</p><p>Cansada de saídas de praia que não refletem sua elegância natural? Imagine-se desfilando com uma peça que une sofisticação artesanal e o toque suave do algodão, transformando cada passo à beira-mar em um momento de puro glamour. Esta é a solução perfeita para quem busca estilo e conforto sem abrir mão da exclusividade.</p><p>
</p><p>Elaborada com a delicadeza do puro algodão, esta saída de praia envolve você em um abraço suave e natural. Sua tonalidade branca imaculada realça o bronzeado e oferece um visual fresco e atemporal, perfeito para qualquer ocasião sob o sol.</p>',
                'marketing_description' => 'Arrase com a Saída De Praia Midi Em Algodão Trançado Macramê – Branco Tamanho G da ModaCrochê. Estilo e conforto garantidos. Compre agora!',
                'price' => '150.00',
                'compare_at_price' => '200.00',
                'cost_price' => '60.00',
                'old_price' => null,
                'stock' => 1,
                'weight' => null,
                'height' => null,
                'width' => null,
                'length' => null,
                'is_active' => 1,
                'card_type' => 'product_standard',
                'condition' => 'new',
                'warranty' => null,
                'origin' => null,
                'ncm' => null,
                'is_offer' => 0,
                'image' => 'products/ai-generated/pollinations_6941c39e12998_1765917598.jpg',
                'created_at' => '2025-12-16 20:36:24',
                'updated_at' => '2025-12-16 20:40:16',
                'product_flavor_id' => null,
                'variant_type' => 'color',
            ],
        ];

        foreach ($data as $item) {
            Product::create($item);
        }

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
